// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx6_pmCyvPQuNnhiDpC2TwHRitRuOvx7s',
    appId: '1:517203874531:web:e2a12629a9b176f29fabd6',
    messagingSenderId: '517203874531',
    projectId: 'project-akhir-ditonton',
    authDomain: 'project-akhir-ditonton.firebaseapp.com',
    storageBucket: 'project-akhir-ditonton.appspot.com',
    measurementId: 'G-DYHC46VNFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmHXKZimrL5w7yNpoV0gsLZxZ-tXr7LRw',
    appId: '1:517203874531:android:cfa32e057dcf4bc59fabd6',
    messagingSenderId: '517203874531',
    projectId: 'project-akhir-ditonton',
    storageBucket: 'project-akhir-ditonton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjzbePlljb45bdfMhaqrvMgJ63cnHtYlw',
    appId: '1:517203874531:ios:ae1e0ef57c3c0d699fabd6',
    messagingSenderId: '517203874531',
    projectId: 'project-akhir-ditonton',
    storageBucket: 'project-akhir-ditonton.appspot.com',
    iosClientId: '517203874531-g2fmtve9inhvag0gg6q8cfogr80fmcne.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
